In [3]:
# list example
fam = [12.3,23,34.6,12.2]
fam

[12.3, 23, 34.6, 12.2]

In [5]:
# List inside list
fam1 = [['aaa',12], ['bbb',34], ['ccc', 54.7]]
fam1

[['aaa', 12], ['bbb', 34], ['ccc', 54.7]]

In [14]:
# Accessing index value in list
fam2 = [12.3,23,34.6,12.2,33.5]
fam2[2]
fam2[-1]
fam2[:-1]
fam2[2:]
fam2[2:4] # it will exclude 6

[34.6, 12.2]

In [15]:
fam[1] = 11
fam

[12.3, 11, 34.6, 12.2]

In [22]:
# pass by ref
x = [3,5,7,8,4,8]
x
y = x # reforing sama list for both X and Y
y[2] = 9
x

[3, 5, 9, 8, 4, 8]

In [32]:
# pass by value
x1 = [4,5,2,9,80,76]
y1 = list(x1) # creates a new list for Y1
y1[3] = 55 # changing only y1[3]
y1 
x1 # no change to x 

[4, 5, 2, 9, 80, 76]

In [33]:
# help () is used to give description about a method
help(round)

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



In [43]:
import numpy as np
np.array([1,2,5,7,3,8])

array([1, 2, 5, 7, 3, 8])

In [41]:
import numpy as np
from numpy import array

array([1,2,3,4])

array([1, 2, 3, 4])

In [55]:
import numpy as np

famh3 = [2,5,7,8,34]
np_height = np.array(famh3)

famw3 = [20,50,70,80,65]
np_wt = np.array(famw3)

bmi = np_wt / np_height ** 2
bmi

array([ 5.        ,  2.        ,  1.42857143,  1.25      ,  0.05622837])

In [58]:
np_wt > 20
n = np_wt > 20
n

array([False,  True,  True,  True,  True], dtype=bool)

In [69]:
import pandas as pd 

brics = pd.read_csv('E:\DataScience\python\AssignmentFilePandas_Updated/brics.csv', index_col = 0)
#brics.index = ['BR','RU','IN','CH','SA']
brics

country    capital    area  population
Code                                             
BR          Brazil   Brasilia   8.516      200.40
RU          Russia     Moscow  17.100      143.50
IN           India  New Delhi   3.286     1252.00
CH           China    Beijing   9.597     1357.00
SA    South Africa   Pretoria   1.221       52.98

In [92]:
#brics['country']
#brics.columns
brics.loc[:,'country']
brics.loc['RU']

country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object